FROM node:20-alpine AS builder

WORKDIR /app
COPY . .
ENV NODE_ENV=production
RUN npm install && npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist .
COPY ./package*.json .
RUN npm install --omit=dev
CMD ["node", "index.cjs"]

