FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app/dist ./
COPY ./package*.json ./
RUN npm prune --production

EXPOSE 5000

CMD ["node", "index.cjs"]